import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable, of, tap } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class ApiService {
  baseUrl = `localhost:3000`;

  constructor(private http: HttpClient) {}

  getRegion(): Observable<Region[]> {
    return of([
      {
        id: 1,
        region: '北部',
        createDate: '2000-01-01',
      },
      {
        id: 2,
        region: '中部',
        createDate: '2000-01-01',
      },
      {
        id: 3,
        region: '南部',
        createDate: '2000-01-01',
      },
      {
        id: 4,
        region: '東部',
        createDate: '2000-01-01',
      },
    ]);
  }

  getLocation(): Observable<Location[]> {
    return of([
      {
        id: '1',
        location: '桃園',
        locationNumber: '500',
        region: '北區',
        address: '市民大道二號',
        isValid: true,
        phone: '03-1111111',
      },
      {
        id: '2',
        location: '新竹',
        locationNumber: '600',
        region: '北區',
        address: '市民大道三號',
        isValid: true,
        phone: '03-2222222',
      },
      {
        id: '3',
        location: '嘉義',
        locationNumber: '700',
        region: '南區',
        address: '市民大道四號',
        isValid: true,
        phone: '03-3333333',
      },
      {
        id: '4',
        location: '屏東',
        locationNumber: '800',
        region: '南區',
        address: '市民大道五號',
        isValid: true,
        phone: '03-4444444',
      },
      {
        id: '5',
        location: '宜蘭',
        locationNumber: '900',
        region: '東區',
        address: '市民大道六號',
        isValid: true,
        phone: '03-5555555',
      },
      {
        id: '6',
        location: '花蓮',
        locationNumber: '1000',
        region: '東區',
        address: '市民大道七號',
        isValid: true,
        phone: '03-6666666',
      },
      {
        id: '7',
        location: '南投',
        locationNumber: '1100',
        region: '中區',
        address: '市民大道八號',
        isValid: true,
        phone: '03-7777777',
      },
      {
        id: '8',
        location: '金門',
        locationNumber: '1200',
        region: '西區',
        address: '市民大道九號',
        isValid: true,
        phone: '03-8888888',
      },
      {
        id: '9',
        location: '澎湖',
        locationNumber: '1300',
        region: '西區',
        address: '市民大道十號',
        isValid: true,
        phone: '03-9999999',
      },
      {
        id: '10',
        location: '連江',
        locationNumber: '1400',
        region: '東區',
        address: '市民大道十一號',
        isValid: true,
        phone: '03-10101010',
      },
      {
        id: '11',
        location: '基隆',
        locationNumber: '1500',
        region: '北區',
        address: '市民大道十二號',
        isValid: true,
        phone: '03-11111112',
      },
      {
        id: '12',
        location: '新北',
        locationNumber: '1600',
        region: '北區',
        address: '市民大道十三號',
        isValid: true,
        phone: '03-13131313',
      },
      {
        id: '13',
        location: '新竹',
        locationNumber: '1700',
        region: '北區',
        address: '市民大道十四號',
        isValid: true,
        phone: '03-14141414',
      },
      {
        id: '14',
        location: '苗栗',
        locationNumber: '1800',
        region: '中區',
        address: '市民大道十五號',
        isValid: true,
        phone: '03-15151515',
      },
      {
        id: '15',
        location: '彰化',
        locationNumber: '1900',
        region: '中區',
        address: '市民大道十六號',
        isValid: true,
        phone: '03-16161616',
      },
      {
        id: '16',
        location: '雲林',
        locationNumber: '2000',
        region: '南區',
        address: '市民大道十七號',
        isValid: true,
        phone: '03-17171717',
      },
      {
        id: '17',
        location: '嘉義',
        locationNumber: '2100',
        region: '南區',
        address: '市民大道十八號',
        isValid: true,
        phone: '03-18181818',
      },
      {
        id: '18',
        location: '台南',
        locationNumber: '2200',
        region: '南區',
        address: '市民大道十九號',
        isValid: true,
        phone: '03-19191919',
      },
      {
        id: '19',
        location: '高雄',
        locationNumber: '2300',
        region: '南區',
        address: '市民大道二十號',
        isValid: true,
        phone: '03-20202020',
      },
      {
        id: '20',
        location: '屏東',
        locationNumber: '2400',
        region: '南區',
        address: '市民大道二十一號',
        isValid: true,
        phone: '03-21212121',
      },
    ]);
  }

  getStaff(): Observable<Staff[]> {
    return of([
      {
        id: 1,
        userName: '張三',
        userId: 'ZS001',
        region: '台北',
        locationNumber: '100',
        gender: '男',
        phone: '0912345678',
        jobName: '工程師',
        arrivalDate: '2022-01-10',
        isValid: true,
        SuperiorNumber: '',
      },
      {
        id: 2,
        userName: '李四',
        userId: 'LS002',
        region: '高雄',
        locationNumber: '200',
        gender: '女',
        phone: '0987654321',
        jobName: '分析師',
        arrivalDate: '2022-03-15',
        isValid: true,
        SuperiorNumber: 'ZS001',
      },
      {
        id: 3,
        userName: '王五',
        userId: 'WW003',
        region: '台中',
        locationNumber: '300',
        gender: '男',
        phone: '0933334444',
        jobName: '經理',
        arrivalDate: '2021-08-20',
        isValid: false,
        SuperiorNumber: 'ZS001',
      },
      {
        id: 4,
        userName: '趙六',
        userId: 'ZL004',
        region: '台南',
        locationNumber: '400',
        gender: '女',
        phone: '0977778888',
        jobName: '主管',
        arrivalDate: '2023-04-05',
        isValid: true,
        SuperiorNumber: 'LS002',
      },
      {
        id: 5,
        userName: '陳七',
        userId: 'CQ005',
        region: '桃園',
        locationNumber: '500',
        gender: '男',
        phone: '0911223344',
        jobName: '開發者',
        arrivalDate: '2022-07-11',
        isValid: true,
        SuperiorNumber: 'WW003',
      },
      {
        id: 6,
        userName: '吳八',
        userId: 'WB006',
        region: '新竹',
        locationNumber: '600',
        gender: '女',
        phone: '0922334455',
        jobName: '設計師',
        arrivalDate: '2022-09-23',
        isValid: true,
        SuperiorNumber: 'ZL004',
      },
      {
        id: 7,
        userName: '鄭九',
        userId: 'ZJ007',
        region: '嘉義',
        locationNumber: '700',
        gender: '男',
        phone: '0933445566',
        jobName: '行銷專員',
        arrivalDate: '2022-12-01',
        isValid: false,
        SuperiorNumber: 'WB006',
      },
      {
        id: 8,
        userName: '林十',
        userId: 'LS008',
        region: '屏東',
        locationNumber: '800',
        gender: '女',
        phone: '0944556677',
        jobName: '專案經理',
        arrivalDate: '2023-02-20',
        isValid: true,
        SuperiorNumber: 'CQ005',
      },
      {
        id: 9,
        userName: '黃一一',
        userId: 'HY011',
        region: '宜蘭',
        locationNumber: '900',
        gender: '男',
        phone: '0955667788',
        jobName: '客服',
        arrivalDate: '2023-05-15',
        isValid: true,
        SuperiorNumber: 'LS008',
      },
      {
        id: 10,
        userName: '蔡一二',
        userId: 'CY012',
        region: '花蓮',
        locationNumber: '1000',
        gender: '女',
        phone: '0966778899',
        jobName: '人力資源',
        arrivalDate: '2023-06-30',
        isValid: false,
        SuperiorNumber: 'HY011',
      },
      {
        id: 11,
        userName: '許一三',
        userId: 'HX013',
        region: '南投',
        locationNumber: '1100',
        gender: '男',
        phone: '0977889900',
        jobName: '財務',
        arrivalDate: '2023-08-10',
        isValid: true,
        SuperiorNumber: 'CY012',
      },
      {
        id: 12,
        userName: '蘇一四',
        userId: 'SY014',
        region: '金門',
        locationNumber: '1200',
        gender: '女',
        phone: '0988990011',
        jobName: '行政助理',
        arrivalDate: '2023-10-05',
        isValid: true,
        SuperiorNumber: 'HX013',
      },
      {
        id: 13,
        userName: '張一五',
        userId: 'ZY015',
        region: '澎湖',
        locationNumber: '1300',
        gender: '男',
        phone: '0999001122',
        jobName: '研究員',
        arrivalDate: '2023-11-20',
        isValid: false,
        SuperiorNumber: 'SY014',
      },
      {
        id: 14,
        userName: '李一六',
        userId: 'LY016',
        region: '連江',
        locationNumber: '1400',
        gender: '女',
        phone: '0911223344',
        jobName: '教師',
        arrivalDate: '2023-12-25',
        isValid: true,
        SuperiorNumber: 'ZY015',
      },
      {
        id: 15,
        userName: '王一七',
        userId: 'WY017',
        region: '基隆',
        locationNumber: '1500',
        gender: '男',
        phone: '0922334455',
        jobName: '藥師',
        arrivalDate: '2024-01-10',
        isValid: true,
        SuperiorNumber: 'LY016',
      },
      {
        id: 16,
        userName: '趙一八',
        userId: 'ZY018',
        region: '新北',
        locationNumber: '1600',
        gender: '女',
        phone: '0933445566',
        jobName: '護士',
        arrivalDate: '2024-03-05',
        isValid: false,
        SuperiorNumber: 'WY017',
      },
      {
        id: 17,
        userName: '周一九',
        userId: 'ZJ019',
        region: '新竹',
        locationNumber: '1700',
        gender: '男',
        phone: '0944556677',
        jobName: '獸醫',
        arrivalDate: '2024-04-20',
        isValid: true,
        SuperiorNumber: 'ZY018',
      },
      {
        id: 18,
        userName: '吳二十',
        userId: 'WB020',
        region: '苗栗',
        locationNumber: '1800',
        gender: '女',
        phone: '0955667788',
        jobName: '廚師',
        arrivalDate: '2024-06-15',
        isValid: true,
        SuperiorNumber: 'ZJ019',
      },
      {
        id: 19,
        userName: '鄭二一',
        userId: 'ZJ021',
        region: '彰化',
        locationNumber: '1900',
        gender: '男',
        phone: '0966778899',
        jobName: '建築師',
        arrivalDate: '2024-08-30',
        isValid: false,
        SuperiorNumber: 'WB020',
      },
      {
        id: 20,
        userName: '林二二',
        userId: 'LS022',
        region: '雲林',
        locationNumber: '2000',
        gender: '女',
        phone: '0977889900',
        jobName: '農夫',
        arrivalDate: '2024-10-05',
        isValid: true,
        SuperiorNumber: 'ZJ021',
      },
      {
        id: 21,
        userName: '黃二三',
        userId: 'HY023',
        region: '嘉義',
        locationNumber: '2100',
        gender: '男',
        phone: '0988990011',
        jobName: '漁夫',
        arrivalDate: '2024-11-20',
        isValid: true,
        SuperiorNumber: 'LS022',
      },
      {
        id: 22,
        userName: '蔡二四',
        userId: 'CY024',
        region: '台南',
        locationNumber: '2200',
        gender: '女',
        phone: '0999001122',
        jobName: '攝影師',
        arrivalDate: '2024-12-25',
        isValid: false,
        SuperiorNumber: 'HY023',
      },
      {
        id: 23,
        userName: '許二五',
        userId: 'HX025',
        region: '高雄',
        locationNumber: '2300',
        gender: '男',
        phone: '0911223344',
        jobName: '記者',
        arrivalDate: '2025-01-10',
        isValid: true,
        SuperiorNumber: 'CY024',
      },
      {
        id: 24,
        userName: '蘇二六',
        userId: 'SY026',
        region: '屏東',
        locationNumber: '2400',
        gender: '女',
        phone: '0922334455',
        jobName: '藝術家',
        arrivalDate: '2025-03-05',
        isValid: true,
        SuperiorNumber: 'HX025',
      },
    ]).pipe(tap((res) => console.log(res)));
  }
}

export interface Region {
  id: number;
  region: string;
  createDate: string;
}

export interface Staff {
  id: number;
  userName: string;
  userId: string;
  region: string;
  locationNumber: string;
  gender: string;
  phone: string;
  jobName: string;
  arrivalDate: string;
  isValid: boolean;
  SuperiorNumber: string;
}

export interface Location {
  id: string;
  location: string;
  locationNumber: string;
  region: string;
  address: string;
  phone: string;
}
